/*
 * components - Graphical interface for converting files to Markdown
 * Copyright 2026 - 2026 Dev2Forge
 * Licence: GPL-3
 * More information: https://github.com/Dev2Forge/bridgex/blob/main/LICENSE
 * Author: tutosrive (tutosriveorg@gmail.com)
 * 
 * File: \h2.slint
 * Created: Sunday, 26th April 2026 5:58:54 pm
 * -----
 * Last Modified: Sunday, 26th April 2026 8:00:58 pm
 * Modified By: tutosrive (tutosriveorg@gmail.com)
 * -----
 */

import { Constants } from "../values/constants.slint";

export component H2 inherits Text {
    font-size: Constants.h2.size;
    font-weight: Constants.h2.weight;
    font-italic: true;

    horizontal-alignment: TextHorizontalAlignment.center;
    vertical-alignment: TextVerticalAlignment.center;
}
