/*
 * ui - Graphical interface for converting files to Markdown
 * Copyright 2026 - 2026 Dev2Forge
 * Licence: GPL-3
 * More information: https://github.com/Dev2Forge/bridgex/blob/main/LICENSE
 * Author: tutosrive (tutosriveorg@gmail.com)
 * 
 * File: \constants.slint
 * Created: Sunday, 26th April 2026 5:33:43 pm
 * -----
 * Last Modified: Monday, 27th April 2026 11:50:58 pm
 * Modified By: tutosrive (tutosriveorg@gmail.com)
 * -----
 */

 import { Palette } from "std-widgets.slint";

 export global Constants {
    out property <{ size: length, weight: float, family: string}> h1: { size: 20px, weight: 900, family: "monospace" };
    out property <{ size: length, weight: float, family: string}> h2: { size: 17px, weight: 700, family: "monospace" };
    out property <{ size: length, weight: float, family: string}> h3: { size: 14px, weight: 600, family: "monospace" };
    out property <length> border_radius_popup: 20px;
    out property <length> preferred_border_radius: 10px;
    out property <length> preferred_padding: 12px;
}

export global Colours {
    out property <color> dark_bg: Palette.alternate-background;
    // #0e0e0edd;
}

export global LibrariesData {
    out property <[{ name: string, url: string}]> libraries: [
        { name: "Bridgex", url: "https://github.com/Dev2Forge/bridgex/blob/main/LICENSE" },
        {
            name: "Markitdown-rs",
            url: "https://github.com/uhobnil/markitdown-rs/blob/master/LICENSE"
        },
        {
            name: "Slint",
            url: "https://github.com/slint-ui/slint/blob/master/LICENSES/GPL-3.0-only.txt"
        }
    ];

    in-out property <string> library_name;
    in-out property <string> library_url;
}

export global RootSizes {
    in-out property <length> width;
    in-out property <length> height;
}

export global PopupSizes {
    out property <{ width: length, height: length}> big_popup: { width: 500px, height: 600px };
}
