/*
 * values - Graphical interface for converting files to Markdown
 * Copyright 2026 - 2026 Dev2Forge
 * Licence: GPL-3
 * More information: https://github.com/Dev2Forge/bridgex/blob/main/LICENSE
 * Author: tutosrive (tutosriveorg@gmail.com)
 * 
 * File: \globals_variables.slint
 * Created: Monday, 27th April 2026 12:22:13 am
 * -----
 * Last Modified: Tuesday, 28th April 2026 11:06:35 pm
 * Modified By: tutosrive (tutosriveorg@gmail.com)
 * -----
 */

export global LicenseDialogData {
    in-out property <string> content;
}
