/*
 * ui - Graphical interface for converting files to Markdown
 * Copyright 2026 - 2026 Dev2Forge
 * Licence: GPL-3
 * More information: https://github.com/Dev2Forge/bridgex/blob/main/LICENSE
 * Author: tutosrive (tutosriveorg@gmail.com)
 * 
 * File: \app-window.slint
 * Created: Saturday, 25th April 2026 11:34:53 pm
 * -----
 * Last Modified: Wednesday, 29th April 2026 3:06:17 pm
 * Modified By: tutosrive (tutosriveorg@gmail.com)
 * -----
 */

import { Button, VerticalBox, GridBox, TextEdit } from "std-widgets.slint";
import { About } from "popups/about.slint";
import { LicenseDialog } from "dialogs/license.slint";
import {
    RootSizes,
    PopupSizes,
    LibrariesData,
    Constants,
} from "values/constants.slint";
import {
    LicenseDialogData,
    FileConverted,
} from "values/globals_variables.slint";

export { LibrariesData }
export { LicenseDialogData }

export component AppWindow inherits Window {
    in-out property <bool> is_maximized: false;
    in-out property <string> filename;
    callback request-increase-value();
    callback request-file-open();
    callback request-license-content();

    callback show_dialog_license();
    callback hide_dialog_license();
    in-out property <string> lib_name;
    in-out property <string> lib_url;

    init => {
        RootSizes.width = self.width;
        RootSizes.height = self.height;
    }

    changed width => {
        RootSizes.width = self.width;
    }
    changed height => {
        RootSizes.height = self.height;
    }

    min-height: 600px;
    min-width: 900px;

    about_popup := About {
        is-hour-to-show-licence-dialog: false;
        callback_show_licence_dialog => show_dialog_license();
    }

    license_dialog := LicenseDialog {
        hide_callback => hide_dialog_license();
    }

    show_dialog_license => {
        request-license-content();
        license_dialog.show();
    }

    hide_dialog_license => {
        license_dialog.close();
    }

    MenuBar {
        Menu {
            title: @tr("MenuBar" => "File");
            MenuItem {
                title: @tr("MenuBar" => "Open");
                shortcut: @keys(Control+O);
                activated => {
                    request-file-open();
                    debug("Open File");
                }
            }
        }

        Menu {
            title: @tr("MenuBar" => "Settings");
            MenuItem {
                title: @tr("MenuBar" => "Theme");
                shortcut: @keys(Control+T);
                activated => {
                    debug("Theme")
                }
            }
        }

        Menu {
            title: @tr("MenuBar" => "Help");
            MenuItem {
                title: @tr("MenuBar" => "About");
                shortcut: @keys(Control+Shift+A);
                activated => {
                    about_popup.show();
                    debug("About");
                }
            }
        }
    }

    GridBox {
        HorizontalLayout {
            TextEdit {
                width: 50%;
                placeholder-text: "Will be the markdown content";
                text: FileConverted.markdown;

                changed text => {
                    FileConverted.markdown = self.text;
                }
            }

            VerticalBox {
                Flickable {
                    viewport-height: preview_markdown.height;

                    preview_markdown := StyledText {
                        width: 100%;
                        text: @markdown("\{FileConverted.markdown}");
                    }
                }
            }
        }
    }
}
