/*
 * ui - Graphical interface for converting files to Markdown
 * Copyright 2026 - 2026 Dev2Forge
 * Licence: GPL-3
 * More information: https://github.com/Dev2Forge/bridgex/blob/main/LICENSE
 * Author: tutosrive (tutosriveorg@gmail.com)
 * 
 * File: \app-window.slint
 * Created: Saturday, 25th April 2026 11:34:53 pm
 * -----
 * Last Modified: Monday, 27th April 2026 3:19:06 pm
 * Modified By: tutosrive (tutosriveorg@gmail.com)
 * -----
 */

import { Button, VerticalBox } from "std-widgets.slint";
import { About } from "popups/about.slint";
import { LicenseDialog } from "dialogs/license.slint";
import { RootSizes, PopupSizes, LibrariesData } from "values/constants.slint";
import { LicenseDialogData } from "values/globals_variables.slint";

export { LibrariesData }
export { LicenseDialogData }

export component AppWindow inherits Window {
    in-out property <string> filename;
    callback request-increase-value();
    callback request-file-open();
    callback request-license-content();

    callback show_dialog_license();
    callback hide_dialog_license();
    in-out property <string> lib_name;
    in-out property <string> lib_url;

    min-height: 500px;
    min-width: 900px;

    about_popup := PopupWindow {
        close-policy: PopupClosePolicy.close-on-click-outside;
        width: PopupSizes.big_popup.width;
        height: PopupSizes.big_popup.height;

        About {
            // x: (RootSizes.width / 2) - self.width / 2;
            // y: (RootSizes.height / 2) - self.height / 2;
            callback_show_licence_dialog => show_dialog_license();
        }
    }

    license_dialog := LicenseDialog {
        hide_callback => hide_dialog_license();
    }

    show_dialog_license => {
        request-license-content();
        license_dialog.show();
    }

    hide_dialog_license => {
        license_dialog.close();
    }

    MenuBar {
        Menu {
            title: @tr("MenuBar" => "File");
            MenuItem {
                title: @tr("MenuBar" => "Open");
                shortcut: @keys(Control+O);
                activated => {
                    request-file-open();
                    debug("Open File");
                }
            }
        }

        Menu {
            title: @tr("MenuBar" => "Settings");
            MenuItem {
                title: @tr("MenuBar" => "Theme");
                shortcut: @keys(Control+T);
                activated => {
                    debug("Theme")
                }
            }
        }

        Menu {
            title: @tr("MenuBar" => "Help");
            MenuItem {
                title: @tr("MenuBar" => "About");
                shortcut: @keys(Control+Shift+A);
                activated => {
                    RootSizes.width = root.width;
                    RootSizes.height = root.height;
                    about_popup.show();
                    debug("About");
                }
            }
        }
    }

    VerticalBox {
        padding: 0;
        spacing: 0;
        height: 100px;
        y: 0;

        Text {
            text: "Filename: \{root.filename}";
        }
    }
}
