/*
 * ui - Graphical interface for converting files to Markdown
 * Copyright 2026 - 2026 Dev2Forge
 * Licence: GPL-3
 * More information: https://github.com/Dev2Forge/bridgex/blob/main/LICENSE
 * Author: tutosrive (tutosriveorg@gmail.com)
 * 
 * File: \constants.slint
 * Created: Sunday, 26th April 2026 5:33:43 pm
 * -----
 * Last Modified: Sunday, 26th April 2026 6:28:44 pm
 * Modified By: tutosrive (tutosriveorg@gmail.com)
 * -----
 */

 export global Constants {
    out property <{ size: length, weight: float, family: string}> h1: { size: 20px, weight: 900, family: "monospace" };
    out property <{ size: length, weight: float, family: string}> h2: { size: 17px, weight: 700, family: "monospace" };
    out property <{ size: length, weight: float, family: string}> h3: { size: 14px, weight: 600, family: "monospace" };
}
