/*
 * dialogs - Graphical interface for converting files to Markdown
 * Copyright 2026 - 2026 Dev2Forge
 * Licence: GPL-3
 * More information: https://github.com/Dev2Forge/bridgex/blob/main/LICENSE
 * Author: tutosrive (tutosriveorg@gmail.com)
 * 
 * File: \license.slint
 * Created: Sunday, 26th April 2026 7:00:59 pm
 * -----
 * Last Modified: Monday, 27th April 2026 12:22:47 am
 * Modified By: tutosrive (tutosriveorg@gmail.com)
 * -----
 */

import {
    Button,
    GridBox,
    StandardButton,
    ScrollView,
    TextEdit,
} from "std-widgets.slint";
import { H1 } from "../components/h1.slint";
import {
    LibrariesData,
    Constants,
    Colours,
    RootSizes,
    PopupSizes,
} from "../values/constants.slint";
import { LicenseDialogData } from "../values/globals_variables.slint";

export component LicenseDialog inherits PopupWindow {
    callback hide_callback();

    width: PopupSizes.big_popup.width;
    height: PopupSizes.big_popup.height;

    close-policy: PopupClosePolicy.no-auto-close;

    VerticalLayout {
        padding: Constants.preferred_padding;
        x: (RootSizes.width / 2) - self.width / 2;
        y: (RootSizes.height / 2) - self.height / 2;

        Rectangle {
            background: Colours.dark_bg;
            border-radius: Constants.border_radius_popup;

            GridBox {
                Row {
                    H1 {
                        text: LibrariesData.library_name;
                    }
                }

                Row {
                    StyledText {
                        text: @markdown("\{LibrariesData.library_url}");

                        link-clicked(link) => {
                            Platform.open-url(link)
                        }
                    }
                }

                Row {
                    Rectangle {
                        background: Colours.dark_bg;
                        height: 70%;
                        border-radius: Constants.preferred_border_radius;

                        HorizontalLayout {
                            padding: Constants.preferred_padding;
                            alignment: center;

                            width: 100%;
                            height: 100%;

                            TextEdit {
                                placeholder-text: "This is a LICENSE text";
                                width: 100%;
                                read-only: true;
                                accessible-item-selectable: false;
                                enabled: false;
                                font-family: "Consolas";
                                text: LicenseDialogData.content;
                                wrap: word-wrap;
                            }
                        }
                    }
                }

                Row {
                    HorizontalLayout {
                        alignment: center;
                        Button {
                            width: 90px;
                            height: 30px;
                            text: @tr("PopupWindow" => "Close");
                            clicked => {
                                hide_callback();
                            }
                        }
                    }
                }
            }
        }
    }
}
