/*
 * dialogs - Graphical interface for converting files to Markdown
 * Copyright 2026 - 2026 Dev2Forge
 * Licence: GPL-3
 * More information: https://github.com/Dev2Forge/bridgex/blob/main/LICENSE
 * Author: tutosrive (tutosriveorg@gmail.com)
 * 
 * File: \license.slint
 * Created: Sunday, 26th April 2026 7:00:59 pm
 * -----
 * Last Modified: Tuesday, 28th April 2026 11:06:16 pm
 * Modified By: tutosrive (tutosriveorg@gmail.com)
 * -----
 */

import {
    Button,
    GridBox,
    StandardButton,
    ScrollView,
    ListView,
} from "std-widgets.slint";
import { H1 } from "../components/h1.slint";
import {
    LibrariesData,
    Constants,
    Colours,
    RootSizes,
    PopupSizes,
} from "../values/constants.slint";
import { LicenseDialogData } from "../values/globals_variables.slint";

export component LicenseDialog inherits PopupWindow {
    callback hide_callback();

    width: PopupSizes.big_popup.width;
    height: PopupSizes.big_popup.height;
    x: (RootSizes.width / 2) - self.width / 2;
    y: (RootSizes.height / 2) - self.height / 2;

    close-policy: PopupClosePolicy.no-auto-close;

    VerticalLayout {
        padding: Constants.preferred_padding;

        Rectangle {
            background: Colours.dark_bg;
            border-radius: Constants.border_radius_popup;

            Button {
                y: ((RootSizes.height / 2) - (layout_main.height / 2)) + 50px;
                opacity: 40%;
                x: ((RootSizes.width / 2) + (root.width / 14)) - 100px;
                z: 1;
                height: 30px;
                icon: @image-url("../images/icons/os.svg");

                clicked => {
                    Platform.open-url(LibrariesData.library_url)
                }
            }

            layout_main := GridBox {
                Row {
                    H1 {
                        text: LibrariesData.library_name;
                    }
                }

                Row {
                    license_container := Rectangle {
                        height: 70%;
                        border-radius: Constants.preferred_border_radius;

                        VerticalLayout {
                            padding: Constants.preferred_padding;

                            license_scroller_container := Flickable {
                                viewport-height: txt.height;

                                txt := Text {
                                    x: 0;
                                    y: 0;
                                    wrap: word-wrap;
                                    width: 100%;
                                    text: LicenseDialogData.content;
                                    font-family: "Consolas";
                                }
                            }
                        }
                    }
                }

                Row {
                    HorizontalLayout {
                        alignment: center;
                        Button {
                            width: 90px;
                            height: 30px;
                            text: @tr("PopupWindow" => "Close");
                            clicked => {
                                hide_callback();
                            }
                        }
                    }
                }
            }
        }
    }
}
