/*
 * popups - Graphical interface for converting files to Markdown
 * Copyright 2026 - 2026 Dev2Forge
 * Licence: GPL-3
 * More information: https://github.com/Dev2Forge/bridgex/blob/main/LICENSE
 * Author: tutosrive (tutosriveorg@gmail.com)
 * 
 * File: \about.slint
 * Created: Sunday, 26th April 2026 12:15:42 pm
 * -----
 * Last Modified: Sunday, 26th April 2026 9:57:17 pm
 * Modified By: tutosrive (tutosriveorg@gmail.com)
 * -----
 */


import {
    ListView,
    Button,
    VerticalBox,
    GridBox,
    AboutSlint,
} from "std-widgets.slint";
import { Constants, LibrariesData, Colours } from "../values/constants.slint";
import { H1 } from "../components/h1.slint";
import { H2 } from "../components/h2.slint";
import { LicenseDialog } from "../dialogs/license.slint";

export component About inherits VerticalLayout {
    padding: 20px;

    in-out property <bool> is_hour_to_show_licence_dialog;
    callback callback_show_licence_dialog();

    Rectangle {
        background: Colours.dark_bg;
        border-radius: Constants.border_radius_popup;

        GridBox {
            H1 {
                text: "About Bridgex";
            }

            Row {
                Image {
                    height: 30%;
                    source: @image-url("../images/icons/logo-bridgex-2.webp");
                }
            }

            Row {
                Text {
                    wrap: TextWrap.word-wrap;
                    text: "Bridgex is an open-source graphical interface that simplifies file-to-Markdown conversion. Built on top of Microsoft's Markitdown library, it provides an intuitive visual experience for users who prefer not to use the command line.";
                }
            }

            Row {
                H1 {
                    text: "Open Source Licences";
                }
            }

            Row {
                GridLayout {
                    spacing: 10px;
                    col: 0;
                    colspan: 1;

                    for library in LibrariesData.libraries: Rectangle {
                        Button {
                            icon: @image-url("../images/icons/os.svg");
                            text: library.name;
                            clicked => {
                                LibrariesData.library_name = library.name;
                                LibrariesData.library_url = library.url;
                                callback_show_licence_dialog()
                            }
                        }
                    }
                }
            }

            Row {
                H2 {
                    text: "Build With";
                }
            }

            Row {
                AboutSlint {
                    height: 100px;
                }
            }
        }
    }
}
